### ISSUE TITLE
Connection problems Joomla 3.10.x sites

### ISSUE THREAD

**Issue by sc00zy** [akeeba/panopticon_connector_j3#4]
Ok here we go. I still have issues connecting Joomla 3.10.x sites to my Panopticon installation. I use the following version as you suggested in the other issue you closed:

Akeeba Panopticon 1.0.1.dev202310231224 on PHP 8.1.24

I get the following error and troubleshooting information:

![Schermafbeelding 2023-10-23 144939](https://github.com/akeeba/panopticon_connector_j3/assets/12911632/4dc69265-c864-49c2-b593-e4a707972dd7)

Troubleshooting information:

![Schermafbeelding 2023-10-23 144901](https://github.com/akeeba/panopticon_connector_j3/assets/12911632/8cbb5cbc-2d26-429d-ae2a-6b71090d8131)

Debug information:

![Schermafbeelding 2023-10-23 144806](https://github.com/akeeba/panopticon_connector_j3/assets/12911632/11ed00c7-7283-4ddd-a9ae-9653333cc1bc)

I cannot access the endpoint url given by the plugin. For example https://www.mywebsite.nl/panopticon_api. I get a 404 not found error.

I am more then happy to provide you with more information or access. Please let me know and thank you in advance.

**Comment by nikosdion** [comment]
> I cannot access the endpoint url given by the plugin. For example https://www.mywebsite.nl/panopticon_api. I get a 404 not found error.

If you try to access the API URL without any authentication information we return 404, the same thing Joomla! would do if you had not installed the plugin. This is an intentional security feature.

> Debug information

The error you get tells me there's a database issue.

I've published a new connector version, 1.0.1. Please try that and tell me if it solved your problem.

**Comment by sc00zy** [comment]
> I've published a new connector version, 1.0.1. Please try that and tell me if it solved your problem.

Tried it, but still no luck and the same error. Now a different message in the HTTP Body of the troubleshooting information. A huge chunk of text I cannot paste here because it may contain sensitive data.

**Comment by nikosdion** [comment]
Can you at least email me that information?

**Comment by sc00zy** [comment]
Yeah your contact form didn't like it very much and flagged it as spam. On what address can I email you directly? Thanks

**Comment by nikosdion** [comment]
It's nicholas at our business domain name.

**Comment by sc00zy** [comment]
I've just send you an email with attached TXT file. I hope it doesn't get stuck in a spam filter or something.

**Comment by nikosdion** [comment]
The content is exactly what we expect the API to return: the full list of extensions installed on your site.

Can you please post a screenshot of _all the other_ troubleshooting information?

**Comment by sc00zy** [comment]
![Schermafbeelding 2023-10-23 161615](https://github.com/akeeba/panopticon_connector_j3/assets/12911632/4be92b11-a117-42e9-b752-9bfc60645920)

**Comment by nikosdion** [comment]
There seemed to be a problem when trying to connect to sites which didn't have SEF URLs with URL rewriting enabled on Joomla! 3. This has been addressed in the [latest dev release](https://www.akeeba.com/download/panopticon-dev/1-0-1-dev202310231802.html). Please install and test.

Note that the first time you get an error, it might suggest that you use a different Endpoint URL in the form `https://www.example.com/index.php/panopticon_api`. Note the `index.php/` in there. **This is a manual action**. Panopticon will **NOT** do that for you, it will only present it as a suggestion.

Moreover, the connector would erroneously recommend the endpoint URL `https://www.example.com/index.php?/panopticon_api` (note the question mark) on some Joomla! 3 sites. This was replaced with the Joomla! 4 API URL by Panopticon, therefore you got an error. This is now caught by Panopticon when you try to create a new site and converted _automatically_ to the correct Endpoint URL in the form `https://www.example.com/index.php/panopticon_api`. This is an automatic action; there is no need for you to do anything.

**Comment by sc00zy** [comment]
This works. Tested with 2 websites now. Great! Thank you for the good work!

**Comment by nikosdion** [comment]
Thank you for the information! With all of you giving me your own little breadcrumbs I was able to follow it back to something reproducible. Once I can reproduce an issue I can fix it.
